### ISSUE TITLE
Maintain an "All ids" array for ordering

### ISSUE THREAD

**Issue by cole-robertson** [brietsparks/normalized-reducer#10]
Hello, you were helping me on StackOverflow and came up with a model for my group and item problem like https://codesandbox.io/s/wonderful-hugle-mcq09?file=/src/App.tsx:3420-3433. 

Right now, when a new item is added it is always above groups that are added at the same level. I have a need in my application to maintain the inserted ordering of these entities, regardless if they are an item or a group. 

Right now there is state like:
```typescript
export interface State extends BaseState {
  entities: {
    group: Record<Id, Group>,
    item: Record<Id, Item>,
  },
  ids: {
    group: Id[],
    item: Id[],
  }
}
```
I was wondering if there was a way to add to that ids section of state to have an allIds array that could automatically hook into the actionCreators.create() statements and add to this array. Is this possible?

Thank you.

**Comment by brietsparks** [comment]
An ordered-ids list containing multiple entity types isn't directly supported, but there are a couple ways to solve it.

Have a single polymorphic entity that can either be a group or file.

```typescript
interface Node {
  id: Id;
  type: 'item'|'group';
  name: string;
  parentId?: Id;
  childIds?: Id;
}

const schema = {
  node: {
    parentId: {
      type: 'node',
      cardinality: 'one',
      reciprocal: 'childIds'
    },
    childIds: {
      type: 'node',
      cardinality: 'many',
      reciprocal: 'parentId'
    }
  }
};
``` 

Or keep separate entities, each with an attribute for ordering, and then write a selector to combine the ordered ids.

```typescript
interface Group {
  id: Id;
  createdAt: Date,
  name: string;
  parentGroupId?: Id,
  childGroupIds?: Id[];
  itemIds?: Id[];
}

interface Item {
  id: Id,
  createdAt: Date,
  name: string;
  groupId: Id
}

// ...
const getGroupContentIds = (state: State, args: { id: Id }) => {
  const group = selectors.getEntity<Group>(state, { type: 'group', id: args.id });
  
  const childGroups = group?.childGroupIds
    ?.map(childGroupId => selectors.getEntity<Group>(state, { type: 'group', id: childGroupId }))
    .filter(childGroup => !!childGroup) as Group[];
  
  const childItems = group?.itemIds
    ?.map(itemIds => selectors.getEntity<Item>(state, { type: 'item', id: itemIds }))
    .filter(item => !!item) as Item[];
  
  return [...childGroups, ...childItems]
    .sort((a, b) => a.createdAt < b.createdAt ? 1 : -1)
    .map(content => content.id);
};
```

**Comment by cole-robertson** [comment]
Thank you for the help! I'm really enjoying the package, you've done great work.
